version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    expose:
      - 5000
    networks:
      server_network_net:
        ipv4_address: 10.0.1.12
  redis:
    image: "redis:latest"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 10.0.1.13

networks:
  server_network_net:
    driver: bridge
    name: server_network
    ipam:
      config:
        - subnet: 10.0.1.0/24